"""Rename 'desciption' to description product

Revision ID: 5f19548dd681
Revises: 84b25f6ca8d7
Create Date: 2024-09-03 16:00:38.516423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f19548dd681'
down_revision: Union[str, None] = '84b25f6ca8d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('description', sa.String(), nullable=False))
    op.drop_column('products', 'desciption')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('desciption', sa.VARCHAR(), nullable=False))
    op.drop_column('products', 'description')
    # ### end Alembic commands ###
