"""Add column count to order product assoication

Revision ID: 12c6aca57958
Revises: 5f19548dd681
Create Date: 2024-09-03 16:28:43.382833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12c6aca57958'
down_revision: Union[str, None] = '5f19548dd681'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_product_association', sa.Column('count', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_product_association', 'count')
    # ### end Alembic commands ###
